name: pecotmr
channels:
  - dnachun
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - clangdev  # [osx]
  - gcc  # [linux]
  - gxx  # [linux]
  - gsl
  - bioconductor-bioccheck
  - r-devtools
  - r-rcmdcheck
  - r-covr
  - r-tidyverse
