{% set version = "VERSION_PLACEHOLDER" %}
{% set name = "pecotmr" %}

package:
  name: r-{{ name }}
  version: {{ version }}

source:
  url: https://github.com/cumc/{{ name }}/archive/{{ version }}.tar.gz
  sha256: SHA256SUM_PLACEHOLDER

build:
  number: BUILD_PLACEHOLDER
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
  host:
    - bioconductor-iranges
    - bioconductor-qvalue
    - bioconductor-s4vectors
    - bioconductor-snpstats
    - r-base=4.3
    - r-bigsnpr
    - r-bigstatsr
    - r-coloc
    - r-data.table
    - r-dofuture
    - r-dplyr
    - r-fsusier
    - r-furrr
    - r-gbj
    - r-ggplot2
    - r-ggnewscale
    - r-ggrepel
    - r-ggvenn
    - r-glmnet
    - r-harmonicmeanp
    - r-magrittr
    - r-matrixstats
    - r-mr.ash.alpha
    - r-mr.mash.alpha
    - r-mvsusier
    - r-pgenlibr
    - r-r.utils
    - r-qgg
    - r-quantreg
    - r-purrr
    - r-r6
    - r-rcpp
    - r-readr
    - r-rfast
    - r-rlab
    - r-stringr
    - r-susier
    - r-tidyr
    - r-udr
    - r-vctrs
  run:
    - bioconductor-iranges
    - bioconductor-qvalue
    - bioconductor-s4vectors
    - bioconductor-snpstats
    - r-base=4.3
    - r-bigsnpr
    - r-bigstatsr
    - r-coloc
    - r-data.table
    - r-dofuture
    - r-dplyr
    - r-fsusier
    - r-furrr
    - r-gbj
    - r-ggplot2
    - r-ggnewscale
    - r-ggrepel
    - r-ggvenn
    - r-glmnet
    - r-harmonicmeanp
    - r-magrittr
    - r-matrixstats
    - r-mr.ash.alpha
    - r-mr.mash.alpha
    - r-mvsusier
    - r-pgenlibr
    - r-purrr
    - r-qgg
    - r-quantreg
    - r-r.utils
    - r-r6
    - r-rcpp
    - r-readr
    - r-rfast
    - r-rlab
    - r-stringr
    - r-susier
    - r-tidyr
    - r-udr
    - r-vctrs

test:
  commands:
    - $R -e "library('{{ name }}')"

about:
  home: https://github.com/cumc/pecotmr
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: pecotmr implements pair-wise enrichment, colocalization, TWAS and Mendelian Randomization to integrate QTL and GWAS analysis based on a fine-mapped single effects model.

extra:
  recipe-maintainers:
    - danielnachun
