name: Post-merge actions

on:
  pull_request_target:
    types: [closed]

jobs:
  update_coverage_badge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main 

      - name: Create YAML from recipe
        run: |
          cp .github/environment/environment.yaml /tmp/environment.yaml
          grep -v '{%' < .github/recipe/meta.yaml | yq .requirements.host | sed 's/^/  /' >> /tmp/environment.yaml

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: /tmp/environment.yaml
          generate-run-shell: true

      - name: Check unit test code coverage
        shell: micromamba-shell {0}
        run: R -e "covr::codecov()"
