name: Upload new release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Version to use for release tag
        required: true
      commit:
        description: Commit to use for tag
        required: false
        default: ${{ GITHUB_SHA }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v3

      - name: Create new tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.events.input.tag }}
          commit_sha: ${{ github.events.input.commit }}
          tag_prefix: ""

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
